Bugfix making sync-rte exit on errors
git-svn-id: svn+ssh://svn.csc.fi/svn/fgi@6498 2bf07f67-1f50-48e5-81db-618ea08fc75d

diff --git a/rpm/fgi-grid-node/fgi-grid-node-2/sync-rte b/rpm/fgi-grid-node/fgi-grid-node-2/sync-rte
--- a/rpm/fgi-grid-node/fgi-grid-node-2/sync-rte
+++ b/rpm/fgi-grid-node/fgi-grid-node-2/sync-rte
@@ -12,9 +12,14 @@ ls /cvmfs/fgi.csc.fi/ &>/dev/null
 
 if [ $? -ne 0 ] ; then
  echo "Could not find cvmfs mount"
+ exit 1;
 fi
 
 cd $cvmfsdir/current
+if [ $? -ne 0 ] ; then
+ echo "Error changing directory to cvmfs"
+ exit 1;
+fi
 
 for f in `find . -type f` ; do 
  d=`dirname $f`
